/**
 * GENERATED by `scripts/gen-staff-fixture.mjs` — do not edit by hand. Regenerate:
 *   pnpm --filter @batch/till staff:fixture:gen
 *
 * A seed staff roster (ADR 0009), standing in for back-office staff sync (Sprint 6), which doesn't
 * exist yet — assumption in docs/assumptions.md, falsifier: back office ships staff sync. Every
 * `pinPhc` is a REAL Argon2id PHC string (m=19456, t=2, p=1, 16-byte random salt); the dev PINs used
 * to produce them are NOT here — see the generator script's header comment.
 */

export type StaffRole = 'MANAGER' | 'STAFF'

export interface StaffFixtureEntry {
  readonly id: string
  readonly name: string
  readonly role: StaffRole
  /** Argon2id PHC string — `verifyPin` (src/auth/pin.ts) checks a typed PIN against this. */
  readonly pinPhc: string
}

export const STAFF_FIXTURE: readonly StaffFixtureEntry[] = [
  { id: "staff-orla", name: "Orla", role: "MANAGER", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$cQGr8pwnqHiea+u9Y00pcA$Zi+YpTRk3ScLJTTh/yc7/T+nH/W/soxz9Km/TVi/xDM" },
  { id: "staff-kyle", name: "Kyle", role: "MANAGER", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$pAWrdN8ZBo5OaZIfPY/o7w$wKmlhj8d6o8tdtyt4bEuaopIwb0OPLK48jDrhrhESkg" },
  { id: "staff-jerry", name: "Jerry", role: "MANAGER", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$fi0nwBEX95XoaZ2TsB3L+w$32aaWEu1AVyiOErr0DAyS26KDlyaMmz1lPI6C6wZ468" },
  { id: "staff-evan", name: "Evan", role: "STAFF", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$vNVxe3N6+mKXKqzvFQ9h+w$5zj/wA2ZFHYMj9KayWbKpfkOJmyYTrFlB1re92xdpL0" },
]
