/**
 * GENERATED by `scripts/gen-staff-fixture.mjs` — do not edit by hand. Regenerate:
 *   pnpm --filter @batch/till staff:fixture:gen
 *
 * A seed staff roster (ADR 0009), standing in for back-office staff sync (Sprint 6), which doesn't
 * exist yet — assumption in docs/assumptions.md, falsifier: back office ships staff sync. Every
 * `pinPhc` is a REAL Argon2id PHC string (m=19456, t=2, p=1, 16-byte random salt); the dev PINs used
 * to produce them are NOT here — see the generator script's header comment.
 */

export type StaffRole = 'MANAGER' | 'STAFF'

export interface StaffFixtureEntry {
  readonly id: string
  readonly name: string
  readonly role: StaffRole
  /** Argon2id PHC string — `verifyPin` (src/auth/pin.ts) checks a typed PIN against this. */
  readonly pinPhc: string
}

export const STAFF_FIXTURE: readonly StaffFixtureEntry[] = [
  { id: "staff-aoife", name: "Aoife", role: "MANAGER", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$cXAi81Ct/V0YDZSJCDn3+A$RvzHj95yp+rk24ZafsNeVhCM5cNgtws49VEQ//zHTBE" },
  { id: "staff-cian", name: "Cian", role: "STAFF", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$inbsQlcL5W4JZSEZItQ8MQ$buvD9m1skfusKEtxmPFK5+e1Bdx+r5j3+P/y86fXPQs" },
  { id: "staff-niamh", name: "Niamh", role: "STAFF", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$ru9+osY9xxonobCVlzo3tg$jfHK0KRQ1nlG300LPbRaNRN7Lj1LlK94qsG21M6gNE8" },
  { id: "staff-darragh", name: "Darragh", role: "STAFF", pinPhc: "$argon2id$v=19$m=19456,t=2,p=1$1ESH4y5aA8FG+S7trm2H0Q$dUiKjzR1OJ8CbT+QV1mB1a2eywWMe2GolVNHyBCEEgQ" },
]
